export const MenuData = [
  {
    title: "Inventory",
    subMenu: [
      {
        title: "Master Barang",
        url: "/master-barang",
        linkClass: "",
        titleClass: "",
        sideBarLinkClass: "",
        sideBarTitleClass: "",
      },
      {
        title: "Kategori Barang",
        url: "/kategori-barang",
        linkClass: "",
        titleClass: "",
        sideBarLinkClass: "",
        sideBarTitleClass: "",
      },
      {
        title: "Barang Masuk",
        url: "/",
        linkClass: "",
        titleClass: "",
        sideBarLinkClass: "",
        sideBarTitleClass: "",
      },
      {
        title: "Barang Keluar",
        url: "/",
        linkClass: "",
        titleClass: "",
        sideBarLinkClass: "",
        sideBarTitleClass: "",
      },
      {
        title: "Barang Reject",
        url: "/",
        linkClass: "",
        titleClass: "",
        sideBarLinkClass: "",
        sideBarTitleClass: "",
      },
      {
        title: "Barang Retur",
        url: "/",
        linkClass: "",
        titleClass: "",
        sideBarLinkClass: "",
        sideBarTitleClass: "",
      },
      {
        title: "Konversi",
        url: "/",
        linkClass: "",
        titleClass: "",
        sideBarLinkClass: "",
        sideBarTitleClass: "",
      },
      {
        title: "Stok Opname",
        url: "/",
        linkClass: "",
        titleClass: "",
        sideBarLinkClass: "",
        sideBarTitleClass: "",
      },
    ]
  },
  {
    title: "Harga",
    subMenu: [
      {
        title: "Harga Beli",
        url: "/",
        linkClass: "",
        titleClass: "",
        sideBarLinkClass: "",
        sideBarTitleClass: "",
      },
      {
        title: "Harga Jual",
        url: "/",
        linkClass: "",
        titleClass: "",
        sideBarLinkClass: "",
        sideBarTitleClass: "",
      },
      {
        title: "Margin",
        url: "/",
        linkClass: "",
        titleClass: "",
        sideBarLinkClass: "",
        sideBarTitleClass: "",
      },
      {
        title: "Diskon",
        url: "/",
        linkClass: "disabled",
        titleClass: "text-gray-500",
        sideBarLinkClass: "disabled",
        sideBarTitleClass: "text-gray-700",
      },
      {
        title: "Ongkos Kirim",
        url: "/",
        linkClass: "disabled",
        titleClass: "text-gray-500",
        sideBarLinkClass: "disabled",
        sideBarTitleClass: "text-gray-700",
      },
    ]
  }
]